version: '3.1'
services:
    mysql:
        image: 'mariadb:10.6'
        environment:
          - MYSQL_ROOT_PASSWORD=123456
          - MYSQL_DATABASE=flask
          - MYSQL_USER=yujian
          - MYSQL_PASSWORD=123456
        ports:
          - "3306:3306"
        container_name: 'mysql'
        volumes:
          - './mysql_data:/var/lib/mysql'
        restart: always
    redis:
        image: 'redis:alpine'
        restart: always
        ports:
          - "6379:6379"
    api:
        build: .
        working_dir: /code
        volumes:
          - ../flask-cli:/code
        command:
          - sh
          - -c
          - |
            export FLASK_APP=migrate.py
            flask db init
            flask db migrate -m 'init'
            flask db upgrade
            export FLASK_APP=app.py
            python app.py
        ports:
          - "8081:5000"
        depends_on:
          - mysql
          - redis
        restart: always